In [6]:
import torch
import numpy as np

In [8]:
x = torch.ones(5)
x

tensor([1., 1., 1., 1., 1.])

In [11]:
b = x.numpy()

In [12]:
print(type(b))

<class 'numpy.ndarray'>


In [16]:
x+=(1)
x

tensor([3., 3., 3., 3., 3.])

## Grad Calc

In [22]:
x = torch.randn(3, requires_grad=True)
x

tensor([ 1.1296,  1.1660, -0.0777], requires_grad=True)

In [23]:
y = x + 2
y

tensor([3.1296, 3.1660, 1.9223], grad_fn=<AddBackward0>)

In [24]:
z = y*y*2
z = z.mean()
z

tensor(15.6759, grad_fn=<MeanBackward0>)

In [25]:
z.backward()


In [26]:
x.grad

tensor([4.1729, 4.2214, 2.5631])